framework:
    workflows:
        buybacks:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'status'
            supports:
                - App\Entity\Buybacks
            initial_marking: pending
            places:
                - pending
                - expired
                - recovered
            transitions:
                expire:
                    from: pending
                    to: expired
                recover:
                    from: pending
                    to: recovered

        deposits_sales:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'status'
            supports:
                - App\Entity\DepositsSales
            initial_marking: pending
            places:
                - pending
                - recovered
                - solded
                - payed
            transitions:
                recover:
                    from: pending
                    to: recovered
                sold:
                    from: pending
                    to: solded
                paid:
                    from: solded
                    to: payed

        advances_payments:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'status'
            supports:
                - App\Entity\AdvancesPayments
            initial_marking: pending
            places:
                - pending
                - expired
                - used
            transitions:
                expire:
                    from: pending
                    to: expired
                use:
                    from: pending
                    to: used
